In [1]:
import numpy as np

In [2]:
escalar = 5
vector = np.array([3,4,5])
matriz = np.array([[1,2],[3,4],[5,6]])
tensor = np.array([
    [[1,2,3,30],[4,5,6,31],[7,8,9,32]],
    [[11,12,13,33],[14,15,16,34],[17,18,19,35]],
    [[21,22,23,36],[24,25,26,37],[7,8,9,38]],
])

# Transposición

En matemática una transposición es el cambio, en una matriz, de filar por columnas.

En Python podemos calcular la transpuesta de un elemento usando el metodo ```.T```

In [3]:
print(matriz,'\n')
print('Dimension', matriz.shape)

[[1 2]
 [3 4]
 [5 6]] 

Dimension (3, 2)


In [4]:
matriz_transpuesta = matriz.T
print(matriz_transpuesta,'\n')
print('Dimension', matriz_transpuesta.shape)

[[1 3 5]
 [2 4 6]] 

Dimension (2, 3)


Podemos hacer la misma operción cuando hablamos de tensores, por ejemplo

In [5]:
print(tensor,'\n')
print('Dimension', tensor.shape)

[[[ 1  2  3 30]
  [ 4  5  6 31]
  [ 7  8  9 32]]

 [[11 12 13 33]
  [14 15 16 34]
  [17 18 19 35]]

 [[21 22 23 36]
  [24 25 26 37]
  [ 7  8  9 38]]] 

Dimension (3, 3, 4)


In [6]:
tensor_transpuesto = tensor.T
print(tensor_transpuesto,'\n')
print('Dimension', tensor_transpuesto.shape)

[[[ 1 11 21]
  [ 4 14 24]
  [ 7 17  7]]

 [[ 2 12 22]
  [ 5 15 25]
  [ 8 18  8]]

 [[ 3 13 23]
  [ 6 16 26]
  [ 9 19  9]]

 [[30 33 36]
  [31 34 37]
  [32 35 38]]] 

Dimension (4, 3, 3)


### ¿Por qué es importante conocer la transpuesta de una matriz?

Una propiedad de las matrices es que la transpuesta de una transpuesta da como resulta la matris original.

Sea $\vec{A}$ una matriz de orden $nxn$ y $\vec{A}^\intercal$ su matriz transpuestas, entonces:

$$(\vec{A}^\intercal)^\intercal = \vec{A}$$

In [7]:
matriz_original = matriz_transpuesta.T
print(matriz_original,'\n')
print(matriz == matriz_original)

[[1 2]
 [3 4]
 [5 6]] 

[[ True  True]
 [ True  True]
 [ True  True]]


Cuando trabajamos con estructuras matriciales este tipo de operaciones son útiles para poder trabajar los despejes en ecuaciones y así obtener datos de forma analítica.

### Propiedades de la transposición

Si $\vec{A}$ , $\vec{B}$ son matrices y $\alpha$ es un escalar, entonces

(I) $(\vec{A}^\intercal)^\intercal = \vec{A}$
<br>
(II) $ (\alpha \vec{A})^\intercal = \alpha \vec{A}^\intercal  $
<br>
(III) $ (\vec{A} + \vec{B})^\intercal = \vec{A}^\intercal + \vec{B}^\intercal$
<br>
(IV) $ (\vec{A} \vec{B})^\intercal = \vec{B}^\intercal \vec{A}^\intercal$

# Suma de matrices

La suma de matrices, solamente esta definida para matrices de iguales dimensiones.

In [8]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[6,5],[4,3],[2,1]])
C = A + B

print('A =\n',A,'\nB=\n',B,'\nC=\n',C)

A =
 [[1 2]
 [3 4]
 [5 6]] 
B=
 [[6 5]
 [4 3]
 [2 1]] 
C=
 [[7 7]
 [7 7]
 [7 7]]


## Matriz más un escalar

Suma a cada elemento de la matriz el valor del escalar

In [9]:
D = A + escalar
print(D)

[[ 6  7]
 [ 8  9]
 [10 11]]


## Sumar matrices con diferentes dimensiones en Python

Anteriormente se dijo que la suma de matrices solo esta definida para matrices que tienen las mismas dimensiones.
<br>
Pero en Python podemos realizar dichas sumas si se cumplen las condiciones para un **broadcasting**

### Broadcasting
Es cuando es posible extender un elemento de menor dimesión hasta completar uno de mayor dimensión.

Por ejemplo:

In [10]:
M_V = matriz_transpuesta + vector
print(M_V,)
print('\n',matriz_transpuesta.shape, vector.shape)

[[ 4  7 10]
 [ 5  8 11]]

 (2, 3) (3,)


Lo que sucede aqui es que al ser $\vec{A}^\intercal$ una matriz de orden $2x3$ y el vector ser de orden $3$ python suma el vector en todas las filas de la matriz. Similar a la suma de matrices con escalares.