In [1]:
import numpy as np

In [2]:
m = np.array([[1,0,0,0,0],
             [0,2,0,0,0],
             [0,0,3,0,0],
             [0,0,0,4,0],
             [0,0,0,0,5]])

In [3]:
det_m = np.linalg.det(m)
print(det_m)

119.99999999999997


In [4]:
a = np.array([2,3])
b = np.array([3,2])

b.dot(a)

12

In [5]:
m = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])
print(m,'\n')
print(m.T)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [6]:
A = np.array([[1,3],[5,6]])
print(A)

[[1 3]
 [5 6]]


In [7]:
B = np.array([1/2,1/2,1/2,1/2])
print(np.linalg.norm(B))

1.0


In [8]:
v = np.array([7,-7,3])
u = np.array([1,1,0])
w = np.array([0,0,1])

In [9]:
(v.dot(u))

0

In [10]:
v.dot(w)

3

In [14]:
A = np.array([[1,-7],
              [1,-3]])
B = np.array([2,5])
print(A)

[[ 1 -7]
 [ 1 -3]]


In [16]:
A_inv = np.linalg.inv(A)
print(A)

[[ 1 -7]
 [ 1 -3]]


In [17]:
A_inv.dot(B)

array([7.25, 0.75])